# Generated by Django 3.1.2 on 2022-08-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('png', 'png'), ('jpg', 'jpg')], default='jpg', max_length=9)),
                ('img', models.ImageField(upload_to='images/profile/')),
            ],
        ),
    ]
