name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
        working-directory: /image_conventor/convertor

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install Poetry
      run: pip install poetry
    - name: Check0
      run: ls
    - name: Change dir
      run: cd convertor
    - name: Check
      run: ls
    - name: Change dir2
      run: cd convertor
    - name: Check2
      run: ls
    - name: Install Dependencies using Poetry
      run: poetry install
    - name: Test with unit tests
      run: poetry python manage.py test
